/**
 * This script will clean all autogenerated data and files:
 * node_modules, yarn.lock, package-lock.json, and the like
 * Usage: node scripts/clean.js <absolute-path>
 */

const fs = require('fs');
const path = require('path');

/**
 * This function will clean all autogenerated data and files:
 * node_modules, yarn.lock, package-lock.json, and the like
 * @param {string} absolutePath
 */
exports.clean = function(absolutePath) {
    fs.rmSync(path.join(absolutePath, 'node_modules'), {recursive: true, force: true});
    fs.rmSync(path.join(absolutePath, 'yarn.lock'), {force: true});
    fs.rmSync(path.join(absolutePath, 'package-lock.json'), {force: true});
    fs.rmSync(path.join(absolutePath, '*.tgz'), {force: true});
}

if (require.main === module) {
    if (process.argv.length < 3) {
        console.error('Usage: node scripts/clean.js <absolute-path>');
        process.exit(1);
    }

    const absolutePath = process.argv[2];
    exports.clean(absolutePath);
}
