const {execSync} = require('child_process');
const {replacePackageVersion} = require("./replacePackageVersion");
const {tgzFileNameToPackageJsonReference} = require('./tgzFileNameToPackageJsonReference.js');
const path = require("path");
const fs = require("fs");
const {TestResult} = require("./TestResult");

exports.Controller = class Controller {
    constructor(absolutePath) {
        this.absolutePath = absolutePath;
    }

    /**
     * This method will clean all autogenerated data and files:
     * node_modules, yarn.lock, package-lock.json, and the like
     */
    clean() {
        /*
         * Clean all autogenerated data and files:
         * node_modules, yarn.lock, package-lock.json, and the like
         */
        fs.rmSync(path.join(this.absolutePath, 'node_modules'), {recursive: true, force: true});
        fs.rmSync(path.join(this.absolutePath, 'package-lock.json'), {force: true});
        fs.rmSync(path.join(this.absolutePath, 'yarn.lock'), {force: true});
        const files = fs.readdirSync(this.absolutePath);
        files.filter(file => file.endsWith('.tgz')).forEach(file => {
            fs.rmSync(path.join(this.absolutePath, file), {force: true});
        });
        return TestResult.ok('clean');
    }

    execSync(cmd) {
        return execSync(cmd, {cwd: this.absolutePath, encoding: 'utf-8'});
    }

    replacePackageJsonVersion(dependencyName, version) {
        const packageJsonPath = path.join(this.absolutePath, 'package.json');
        return replacePackageVersion(packageJsonPath, dependencyName, version)
    }

    tgzFileNameToPackageJsonReference(tgzFileName) {
        return tgzFileNameToPackageJsonReference(this.absolutePath, tgzFileName);
    }
}